// LOCALHOST
### Get all contacts 

GET http://localhost:3000/contacts

### Get contact by id

GET http://localhost:3000/contacts/67da3374b2d97e8a9649e690

### Create contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Juliette",
  "lastName": "Sorensen",
  "email": "sorenjul@test.net",
  "favoriteColor": "Marine",
  "birthday": "05-13-1985"
}

### Update contact
PUT http://localhost:3000/contacts/67da3374b2d97e8a9649e690 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Amy",
    "lastName": "Fisher",
    "email": "amfisher@test.net",
    "favoriteColor": "Blue",
    "birthday": "05-29-1985"
}

### Delete contact
DELETE http://localhost:3000/contacts/67da31f0b2d97e8a9649e68f HTTP/1.1
Content-Type: application/json

// LOCALHOST
### Get all temples

GET http://localhost:3000/temples

### Get temple by id

GET http://localhost:3000/temples/67e334cd0b6307ed073997c6
### Create temple
POST http://localhost:3000/temples HTTP/1.1
Content-Type: application/json

{
  "temple_id": "301",
  "additionalInfo": "false",
  "name": "Antananarivo Madagascar Temple",
  "location": "Antananarivo Madagascar",
  "dedicated": "03-08-2025"
}

### Update contact
PUT http://localhost:3000/temples/67e336892468bffb5a2151f5 HTTP/1.1
Content-Type: application/json

{
  "temple_id": 305,
  "additionalInfo": "false",
  "name": "Antananarivo Madagascar Temple",
  "location": "Andranomena Antananarivo Madagascar",
  "dedicated": "03-08-2025"
}

### Delete contact
DELETE http://localhost:3000/temples/67e336892468bffb5a2151f5 HTTP/1.1
Content-Type: application/json


